### ISSUE TITLE
PHP Fatal error:  Cannot acquire reference to $GLOBALS in /home/lol/public_html/includes/style.php on line 334

### ISSUE THREAD

**Issue by mehmet9978** [awssat/kleeja#240]
Hello, I am getting this error, I cannot find the solution, I would be very happy if you could help me.

**Comment by RouatbiH** [comment]
This issue occurs because Kleeja 3.1.6 officially supports PHP 7, and the error is caused by changes in how PHP 8 handles references to $GLOBALS. Since you're using PHP 8, I recommend downgrading your PHP version to PHP 7 to ensure compatibility.

Alternatively, we have a pre-release version (3.1.7) that supports PHP 8. However, please note that it is still in testing and not recommended for production environments. If you'd like to try the pre-release version, proceed with caution and ensure thorough testing.

Let us know if you need further assistance!
